# Generated by Django 2.0.7 on 2018-07-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
