# Generated by Django 2.0.7 on 2018-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20180709_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
